services:
  db:
    image: mysql:8.0
    container_name: onlineshop-mysql-test
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onlineshop
      MYSQL_USER: shopuser
      MYSQL_PASSWORD: shoppass
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./text1.2.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    image: onlineshop-backend:latest
    container_name: onlineshop-backend-test
    ports:
      - "8081:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/onlineshop?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: shopuser
      SPRING_DATASOURCE_PASSWORD: shoppass
      MEDIA_UPLOAD_DIR: /app/uploads
      MEDIA_BASE_URL: http://120.55.249.112:8081/media
    volumes:
      - ./uploads:/app/uploads
  frontend:
    image: onlineshop-frontend:latest
    container_name: onlineshop-frontend-test
    ports:
      - "80:80"
    depends_on:
      - backend
