ai:
  api:
    key: ${ALI_API_KEY:}
    base-url: https://dashscope.aliyuncs.com/api/v1
    connect-timeout-ms: 30000
    read-timeout-ms: 120000
    retry-times: 2
    embedding-model: text-embedding-v4
  session:
    ttl-ms: 1800000

rag:
  vector:
    index-ttl-ms: 300000
    min-score: 0.50

media:
  upload-dir: D:/Onlineshop/backend/uploads
  base-url: http://localhost:8080/media

baidu:
  nlp:
    api-key: hnwBITFfIqfAuJJ0oXGJloiV
    secret-key: 5A24zuHlN5ErP8X8Dyqj7avUFACOiOqc